baseURL = 'https://JujiaLi2020.github.io/Jujia-academic-card/'
languageCode = 'en-us'
title = 'Julia | Psychometrician'
theme = 'PaperMod'

[params]
    defaultTheme = 'auto'
    showReadingTime = true
    
    # 开启首页名片模式
    [params.profileMode]
        enabled = true
        title = "Jujia (J)"
        subtitle = "Ph.D. Candidate in Computational Psychometrics | Developer of PsyMAS"
	# 如果你没有照片，建议先删除或注释掉 imageUrl 行
        # imageUrl = "https://your-photo.jpg" 
        imageWidth = 120   # 限制头像宽度
        imageHeight = 120  # 限制头像高度
        
        [[params.profileMode.buttons]]
            name = "Explore PsyMAS"
            url = "/posts/ps-mas-introduction"
        [[params.profileMode.buttons]]
            name = "LinkedIn"
            url = "https://www.linkedin.com/in/jujia-li-a1905a172/"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/JujiaLi2020/psych-mas"
    [[params.socialIcons]]
        name = "email"
        url = "mailto:jli183@crimson.ua.edu"